[package]
name = "dw"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
reqwest = { version = "0.12.24", features = ["json", "blocking"] }
serde = { version = "1.0.228", features = ["derive"] }
